# Generated by Django 4.1.5 on 2023-04-30 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myGIM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myGIM.contact'),
        ),
    ]
