# Generated by Django 4.1.5 on 2023-05-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myGIM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='time',
            field=models.CharField(choices=[('6:00am - 8:00am', '6:00am - 8:00am'), ('8:00am - 10:00am', '8:00am - 10:00am'), ('10:00am - 1:00pm', '10:00am - 1:00pm'), ('1:00pm - 3:00pm', '1:00pm - 3:00pm'), ('3:00pm - 5:00pm', '3:00pm - 5:00pm'), ('5:00pm - 8:00pm', '5:00pm - 8:00pm'), ('8:00pm - 10:00pm', '8:00pm - 10:00pm')], max_length=100),
        ),
    ]
