# Generated by Django 4.2 on 2023-05-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myGIM', '0002_alter_timetable_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('img', models.ImageField(blank=True, null=True, upload_to='photo/')),
            ],
        ),
    ]
