# Generated by Django 4.1.5 on 2023-04-30 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myGIM', '0002_alter_feedback_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
