# Generated by Django 4.1.5 on 2023-05-03 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myGIM', '0003_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='community',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
