# Generated by Django 4.2 on 2023-05-03 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myGIM', '0004_gallery_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectdate', models.DateTimeField(auto_now=True)),
                ('login', models.CharField(max_length=200)),
                ('logout', models.CharField(max_length=200)),
                ('selectWorkout', models.CharField(max_length=200)),
                ('trainedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myGIM.trainer')),
            ],
        ),
    ]
